[package]
name = "ansine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
axum = "0.6.6"
nom = "7.1.3"
tokio = { version = "1.25.0", features = [ "full" ] }
